{
 "title": "Hygie",
 "description": "Hygie Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Error rate in %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"^4..$\"}[5m])) /  sum(http_request_duration_ms_sum) * 100"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_request_duration_ms_count) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[1m])) by (route, method, code)  * 60",
     "legendFormat": "{{method}} {{route}} {{code}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Nb requests / route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(http_request_duration_ms_count) by (route))\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Nb requests / code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(http_request_duration_ms_count) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Nb requests / method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(http_request_duration_ms_count) by (method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1024 / 1024) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}